## Creating SQL database

In [1]:
import sqlite3

conn = sqlite3.connect("../sql/bike_sharing.db")

In [2]:
import pandas as pd
data_days = pd.read_csv("../data/processed/data_days.csv")

In [3]:
data_days.to_sql("daily_rentals", conn, if_exists="replace", index=False)

731

In [4]:
conn.commit()

## Initial queries

In [5]:
query = """
SELECT *
FROM daily_rentals
LIMIT 5;
"""

pd.read_sql_query(query, conn)

,instant,dteday,season,yr,mnth,holiday,weekday,workingday,weathersit,temp,atemp,hum,windspeed,casual,registered,cnt
0,1,2011-01-01,1,0,1,0,6,0,2,0.344167,0.363625,0.805833,0.160446,331,654,985
1,2,2011-01-02,1,0,1,0,0,0,2,0.363478,0.353739,0.696087,0.248539,131,670,801
2,3,2011-01-03,1,0,1,0,1,1,1,0.196364,0.189405,0.437273,0.248309,120,1229,1349
3,4,2011-01-04,1,0,1,0,2,1,1,0.200000,0.212122,0.590435,0.160296,108,1454,1562
4,5,2011-01-05,1,0,1,0,3,1,1,0.226957,0.229270,0.436957,0.186900,82,1518,1600

In [10]:
query = """ 
SELECT weathersit, AVG(cnt) AS avg_rentals
FROM daily_rentals
GROUP BY weathersit
"""
pd.read_sql_query(query, conn)

   weathersit  avg_rentals
0           1  4876.786177
1           2  4035.862348
2           3  1803.285714

In [13]:
query = """ 
    SELECT yr AS year, AVG(cnt) AS avg_rentals
    FROM daily_rentals
    GROUP BY yr
"""
pd.read_sql_query(query, conn)

   year  avg_rentals
0     0  3405.761644
1     1  5599.934426